services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: collection_rabbitmq    
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - collection-network

  auth-api:    
    container_name: collection_auth_api
    build:
      context: .
      dockerfile: AuthApi/Dockerfile 
    env_file:
      - AuthApi/.env 
    ports:
      - "5011:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq 
    depends_on:
      - rabbitmq
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys  
    networks:
      - collection-network

  outbox-worker:
    build:
      context: .
      dockerfile: CollectionOutbox/Dockerfile
    container_name: collection_outbox_worker
    env_file:
      - CollectionOutbox/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - collection-network

  email-worker:
    build:
      context: .
      dockerfile: CollectionEmail/Dockerfile
    container_name: collection_email_worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - collection-network

networks:
  collection-network:
    driver: bridge

volumes:
  rabbitmq_data:
  